Repository ormcamp-fe-3rd/radian, pull requests merged in 2024-12, with the labels that each got.

#18 [김수진]상품 상세 페이지 ui 구현과 스크롤 트리거 애니메이션 구현
  .gitignore
  dist/assets/index-6hXYWri4.js
  dist/assets/index-BSGrIHMe.css
  dist/assets/index-DULKO8J3.js
  dist/assets/index-h5pTzabl.css
  dist/images/ProductDetail/CAR SAFETY.png
  dist/images/ProductDetail/CAR-INTERIOR.png
  dist/images/ProductDetail/car-front.png
  dist/images/ProductDetail/car-perfonmance.png
  dist/images/ProductDetail/car-performance2.png
  dist/images/ProductDetail/car-side.png
  dist/images/ProductDetail/detail-car-side.png
  dist/images/ProductDetail/detail-car1.png
  dist/images/ProductDetail/detail-car2.png
  dist/images/ProductDetail/radian-rover-side.webp
  dist/images/ProductDetail/range-rover-header.jfif
  dist/images/common/Facebook-icon.png
  dist/images/common/Github-icon.png
  dist/images/common/Instagram-icon.png
  dist/images/common/Twitter-icon.png
  dist/images/common/go-list.png
  dist/images/common/go-profile.png
  dist/images/common/logo.png
  dist/index.html
  package-lock.json
  package.json
  public/images/ProductDetail/CAR SAFETY.png
  public/images/ProductDetail/CAR-INTERIOR.png
  public/images/ProductDetail/car-front.png
  public/images/ProductDetail/car-perfonmance.png
  public/images/ProductDetail/car-performance2.png
  public/images/ProductDetail/car-side.png
  public/images/ProductDetail/detail-car-side.png
  public/images/ProductDetail/detail-car1.png
  public/images/ProductDetail/detail-car2.png
  public/images/ProductDetail/radian-rover-side.webp
  public/images/ProductDetail/range-rover-header.jfif
  public/images/common/Facebook-icon.png
  public/images/common/Github-icon.png
  public/images/common/Instagram-icon.png
  public/images/common/Twitter-icon.png
  public/images/common/go-list.png
  public/images/common/go-profile.png
  public/images/common/logo.png
  src/App.tsx
  src/components/CarImgHalf.tsx
  src/components/CarImgSingle.tsx
  src/components/CarImgTriple.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/HeaderLogin.tsx
  src/components/LoginForm.tsx
  src/components/Timeline.tsx
  src/pages/Login.tsx
  src/pages/ProductDetail.tsx
  src/styles/Footer.css
  src/styles/Header.css
  src/styles/ProductDetail.css
Labels: Feature, reviewer request

#28 [김수진]메인 머지 밑작업
  src/App.tsx
  src/pages/Home.tsx
  src/pages/Register.tsx
Labels: test

#29 [김수진]메인에 로그인, 상품 상세 페이지 머지
  .gitignore
  README.md
  dist/assets/Danfo-Regular-VariableFont_ELSH-DBPCMlg6.ttf
  dist/assets/index-6hXYWri4.js
  dist/assets/index-h5pTzabl.css
  dist/fonts/Alkalami/Alkalami-Regular.ttf
  dist/fonts/Danfo/Danfo-Regular-VariableFont_ELSH.ttf
  dist/fonts/Diplomata/Diplomata-Regular.ttf
  dist/fonts/Faster_One/FasterOne-Regular.ttf
  dist/fonts/JosefinSlab/JosefinSlab-VariableFont_wght.ttf
  dist/fonts/LINESeedKR/LINESeedKR-Bd.woff2
  dist/fonts/LINESeedKR/LINESeedKR-Rg.woff2
  dist/fonts/LINESeedKR/LINESeedKR-Th.woff2
  dist/images/ProductDetail/CAR SAFETY.png
  dist/images/ProductDetail/CAR-INTERIOR.png
  dist/images/ProductDetail/car-front.png
  dist/images/ProductDetail/car-perfonmance.png
  dist/images/ProductDetail/car-performance2.png
  dist/images/ProductDetail/car-side.png
  dist/images/ProductDetail/detail-car-side.png
  dist/images/ProductDetail/detail-car1.png
  dist/images/ProductDetail/detail-car2.png
  dist/images/ProductDetail/radian-rover-side.webp
  dist/images/ProductDetail/range-rover-header.jfif
  dist/images/common/Facebook-icon.png
  dist/images/common/Github-icon.png
  dist/images/common/Instagram-icon.png
  dist/images/common/Twitter-icon.png
  dist/images/common/go-list.png
  dist/images/common/go-profile.png
  dist/images/common/logo.png
  dist/index.html
  package-lock.json
  package.json
  public/images/ProductDetail/CAR SAFETY.png
  public/images/ProductDetail/CAR-INTERIOR.png
  public/images/ProductDetail/car-front.png
  public/images/ProductDetail/car-perfonmance.png
  public/images/ProductDetail/car-performance2.png
  public/images/ProductDetail/car-side.png
  public/images/ProductDetail/detail-car-side.png
  public/images/ProductDetail/detail-car1.png
  public/images/ProductDetail/detail-car2.png
  public/images/ProductDetail/radian-rover-side.webp
  public/images/ProductDetail/range-rover-header.jfif
  src/App.tsx
  src/components/CarImgHalf.tsx
  src/components/CarImgSingle.tsx
  src/components/CarImgTriple.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/LoginForm.tsx
  src/pages/Detail.tsx
  src/pages/Login.tsx
  src/pages/ProductDetail.tsx
  src/styles/Detail.css
  src/styles/Header.css
  src/styles/Login.css
  src/styles/ProductDetail.css
Labels: test

#33 [김도연]npm run build 오류 사항 수정
  package-lock.json
  package.json
  src/components/CarObicontrol.tsx
  src/types/three-externals.d.ts
Labels: bug

#43 [김도연] 상품 리스트 페이지 반응형 작업
  src/components/CarListDetail.tsx
  src/components/ScrollPanel.tsx
  src/data/modelsData.json
  src/pages/ProductDetail.tsx
  src/styles/CarList.css
  src/styles/CarListDetail.css
  src/styles/ProductList.css
  src/styles/reset.css
Labels: reviewer request

#42 [박한솔] 회원가입 페이지 리팩토링
  README.md
  src/components/SignInForm.tsx
  src/components/SignUpForm.tsx
  src/data/signUpFormType.ts
  src/data/signUpFormat.tsx
  src/pages/Register.tsx
Labels: Refector, reviewer request

#49 [김수진]상세페이지 피드백 반영 및 리팩토링
  , selectedModel } = carData
  dist/assets/index-Bgtgx9RX.js
  dist/assets/index-ClZZx36D.css
  dist/assets/index-D7cKWtZ4.js
  dist/assets/index-DHmxp7wz.css
  dist/images/ProductDetail/cooper-header.jpg
  dist/images/ProductDetail/cooper-vintage.jfif
  dist/images/ProductDetail/radian-cooper-side.webp
  dist/images/ProductDetail/radian-rd6-side.webp
  dist/images/ProductDetail/rd6-header.jpg
  dist/images/ProductDetail/rd6-vintage.jpg
  dist/images/ProductDetail/rover-vintage.jpg
  dist/images/main-images/Classic-Mini-Appeal.jpg
  dist/images/main-images/Mini-Cooper-Classic-Electric-conversion-1.webp
  dist/images/main-images/Mini-EV-Conversion.jpg
  dist/images/main-images/cooper-old.png
  dist/images/main-images/mini-new.jpg
  dist/images/main-images/new-TR6.jpeg
  dist/images/main-images/old-TR6-2.jpg
  dist/images/main-images/old-TR6.png
  dist/images/main-images/old-rover.jpg
  dist/images/main-images/range-rover-new.jpg
  dist/index.html
  public/images/ProductDetail/cooper-header.jpg
  public/images/ProductDetail/cooper-vintage.jfif
  public/images/ProductDetail/radian-cooper-side.webp
  public/images/ProductDetail/radian-rd6-side.webp
  public/images/ProductDetail/rd6-header.jpg
  public/images/ProductDetail/rd6-vintage.jpg
  public/images/ProductDetail/rover-vintage.jpg
  src/App.tsx
  src/components/CarList.tsx
  src/components/LoginForm.tsx
  src/components/ProductDetailIntro.tsx
  src/components/ScrollHeader.tsx
  src/components/ScrollPanel.tsx
  src/components/ScrollPanelChars.tsx
  src/components/ScrollPanelSpecs.tsx
  src/components/ScrollRotator.tsx
  src/data/ProductList.json
  src/data/modelsData.json
  src/hooks/useProductDetailScroll.tsx
  src/pages/ProductDetail.tsx
  src/pages/ProductList.tsx
  src/styles/ProductDetail.css
  src/types/modelsTypes.ts
  t ScrollPanel = ({ carData } ScrollPanelProps) = {
Labels: Refector, Feature, Code review request

#53 [박한솔] index 페이지 리팩토링 점검
  src/components/Footer.tsx
  src/components/Home/CardFlipSection.tsx
  src/components/Home/CardHoverSection.tsx
  src/components/Home/CardZoomSection.tsx
  src/components/Home/TitleSection.tsx
  src/components/Home/VideoSection.tsx
  src/components/Register/Agreement.tsx
  src/components/Register/SignUpForm.tsx
  src/data/Home/companyVision.tsx
  src/data/Home/indexCarImagePath.json
  src/data/Register/signUpFormat.tsx
  src/data/Register/terms.json
  src/pages/Home.tsx
  src/styles/Login.css
  src/styles/Register.css
Labels: Refector, reviewer request

#52 [김도연]상품리스트페이지 type 선언 별도 파일로 분리
  README.md
  src/components/Login/LoginForm.tsx
  src/components/ProductList/CarCarousel.tsx
  src/components/ProductList/CarList.tsx
  src/components/ProductList/CarListDetail.tsx
  src/data/ProductList.json
  src/pages/ProductList.tsx
  src/styles/ProductorList/CarCarousel.css
  src/styles/ProductorList/CarList.css
  src/styles/ProductorList/CarListDetail.css
  src/styles/ProductorList/ProductList.css
  src/types/CarProductTypes.ts
Labels: Refector, reviewer request

#54 [김수진]상세페이지 리뷰 요청
  public/images/ProductDetail/cooper-safety1.webp
  public/images/ProductDetail/cooper-safety2.webp
  public/images/ProductDetail/cooper-safety3.webp
  public/images/ProductDetail/cooper-safety4.webp
  public/images/ProductDetail/cooper-safety5.webp
  public/images/ProductDetail/cooper-safety6.webp
  public/images/ProductDetail/cooper-safety7.webp
  public/images/ProductDetail/cooper-safety8.webp
  public/images/ProductDetail/cooper-safety9.webp
  public/images/ProductDetail/rover-safety1.webp
  public/images/ProductDetail/rover-safety2.webp
  public/images/ProductDetail/rover-safety3.webp
  public/images/ProductDetail/rover-safety4.webp
  public/images/ProductDetail/rover-safety5.webp
  public/images/ProductDetail/rover-safety6.webp
  public/images/ProductDetail/rover-safety7.webp
  public/images/ProductDetail/rover-safety8.webp
  public/images/ProductDetail/rover-safety9.webp
  public/images/ProductDetail/safety1.webp
  public/images/ProductDetail/safety2.webp
  public/images/ProductDetail/safety3.webp
  public/images/ProductDetail/safety4.webp
  public/images/ProductDetail/safety5.webp
  public/images/ProductDetail/safety6.webp
  public/images/ProductDetail/safety7.webp
  public/images/ProductDetail/safety8.webp
  public/images/ProductDetail/safety9.webp
  src/components/ProductDetail/Articles.tsx
  src/components/ProductDetail/GoListIcon.tsx
  src/components/ProductDetail/OptionsIcon.tsx
  src/components/ProductDetail/ProductDetailIntro.tsx
  src/components/ProductDetail/Safety.tsx
  src/components/ProductDetail/ScrollHeader.tsx
  src/components/ProductDetail/ScrollPanel.tsx
  src/components/ProductDetail/ScrollPanelChars.tsx
  src/components/ProductDetail/ScrollPanelSpecs.tsx
  src/components/ProductDetail/ScrollRotator.tsx
  src/components/ProductDetail/WrapMaskImg.tsx
  src/data/modelsData.json
  src/hooks/useProductDetailScroll.tsx
  src/pages/ProductDetail.tsx
  src/styles/ProductDetail.css
  src/types/modelsTypes.ts
Labels: reviewer request

#56 [김수진]상세페이지 머지
  src/components/ProductDetail/Safety.tsx
  src/styles/ProductDetail.css
Labels: Refector

#57 [김수진]상세페이지 오타
  src/components/ProductDetail/Articles.tsx
  src/components/ProductDetail/ProductDetailIntro.tsx
Labels: Refector

#55 [김우주] 2차 피드백 적용
  src/components/CarObicontrol.tsx
  src/components/CarObicontrolCompact.tsx
  src/components/CarObicontrolSport.tsx
  src/components/CarObicontrolUtility.tsx
  src/components/CarOption.tsx
  src/components/CarOptionCompact.tsx
  src/components/CarOptionSport.tsx
  src/components/CarOptionUtility.tsx
  src/types/carOptionTypes.ts
  src/types/three.d.ts
Labels: reviewer request
